#!/usr/bin/env bash
#
# generate-dummy-changes.sh — build the test data release.sh chews on.
#
# Every commit appends one line to DUMMY-COMMITS-TARGET.md, so the repository
# stays trivial while the commit history gets interesting. The dataset covers
# every rule of the release script:
#
#   * features with and without an issue reference
#   * bug fixes, all with an issue reference
#   * a breaking change flagged with "!" and one flagged in the commit body
#   * other conventional types (docs, ci, chore, test, style)
#   * a reference to a number that is not a real issue, to prove the script
#     falls back to the commit link instead of inventing a title
#
# The issue numbers come from tests/dummy-issues.env, written by
# tests/create-dummy-issues.sh. Run that first.
#
# These are real commits on the current branch: use a scratch repository.

set -euo pipefail

PUSH=false
TARGET="DUMMY-COMMITS-TARGET.md"
RECORD="COMMIT-MESSAGES.md"
ENV_FILE="tests/dummy-issues.env"

usage() {
  cat <<EOF
$(basename "$0") — generate the dummy conventional commits.

Usage: $(basename "$0") [options]

Options:
  -p, --push    Push the commits to origin when done.
  -h, --help    Show this help.

Writes the commits to ${TARGET} and the human-readable recap to ${RECORD}.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -p | --push) PUSH=true; shift ;;
    -h | --help) usage; exit 0 ;;
    *)           usage >&2; exit 1 ;;
  esac
done

git rev-parse --is-inside-work-tree >/dev/null 2>&1 || {
  printf 'not inside a git repository\n' >&2; exit 1
}
cd "$(git rev-parse --show-toplevel)"

[[ -f $ENV_FILE ]] || {
  printf '%s not found — run ./tests/create-dummy-issues.sh first\n' "$ENV_FILE" >&2
  exit 1
}
# shellcheck disable=SC1090
source "$ENV_FILE"

[[ -f $TARGET ]] || printf '# Dummy commits target\n\nEvery dummy commit appends one line below.\n\n' >"$TARGET"

: >"$RECORD"
{
  printf '# Dummy commit messages\n\n'
  printf 'Generated by `tests/generate-dummy-changes.sh` on %s.\n\n' "$(date '+%Y-%m-%d %H:%M:%S')"
  printf 'Check that `release.sh` classifies every line the way the last two columns say.\n'
  printf 'The bump expected from this whole set is **major**, because of the breaking changes.\n\n'
  printf '| # | Commit | Message | Expected section | Expected entry in the notes |\n'
  printf '|---|--------|---------|------------------|-----------------------------|\n'
} >>"$RECORD"

COUNT=0

# commit <expected section> <expected entry> <subject> [body]
commit() {
  local section="$1" expected="$2" subject="$3" body="${4:-}" short
  COUNT=$((COUNT + 1))

  printf -- '- %s\n' "$subject" >>"$TARGET"
  git add "$TARGET"
  if [[ -n $body ]]; then
    git commit --quiet -m "$subject" -m "$body"
  else
    git commit --quiet -m "$subject"
  fi

  short=$(git rev-parse --short HEAD)
  printf '| %s | `%s` | `%s` | %s | %s |\n' \
    "$COUNT" "$short" "$subject" "$section" "$expected" >>"$RECORD"
  printf '  %-2s %s %s\n' "$COUNT" "$short" "$subject"
}

printf 'Generating the dummy commits in %s\n\n' "$TARGET"

printf 'Other changes:\n'
commit "Others" "message + commit link" \
  "docs: explain the release flow in the readme"
commit "Others" "message + commit link" \
  "ci: run the release script in dry-run on pull requests"
commit "Others" "message + commit link" \
  "chore(deps): bump the linter to 9.0.0"
commit "Others" "message + commit link" \
  "test: cover the version bump rules"
commit "Others" "message + commit link" \
  "style: reformat the release script"

printf '\nBug fixes:\n'
commit "Bug fixes" "title of issue #${FIX_ISSUE_1}" \
  "fix: keep the cart total in sync (#${FIX_ISSUE_1})"
commit "Bug fixes" "title of issue #${FIX_ISSUE_2}" \
  "fix(api): return 404 instead of 500 on unknown order (#${FIX_ISSUE_2})"
commit "Bug fixes" "title of issue #${FIX_ISSUE_3}" \
  "fix: stop the login form from eating the password (#${FIX_ISSUE_3})"

printf '\nFeatures:\n'
commit "Features" "title of issue #${FEATURE_ISSUE_1}" \
  "feat: export the orders as CSV (#${FEATURE_ISSUE_1})"
commit "Features" "title of issue #${FEATURE_ISSUE_2}" \
  "feat(billing): add the monthly invoices (#${FEATURE_ISSUE_2})"
commit "Features" "message + commit link (no issue referenced)" \
  "feat: dark mode for the dashboard"
commit "Features" "message + commit link (#9999 is not a real issue)" \
  "feat(search): remember the last query (#9999)"

printf '\nBreaking changes:\n'
commit "BREAKING CHANGES" "title of issue #${BREAKING_ISSUE_1}" \
  "feat!: drop the v1 authentication endpoints (#${BREAKING_ISSUE_1})"
commit "BREAKING CHANGES" "message + commit link (flagged in the body)" \
  "refactor: move the supabase client to its own module" \
  "BREAKING CHANGE: the supabase client is no longer exported from index.js"

printf '\n%s commits added on %s. Recap written to %s\n' \
  "$COUNT" "$(git rev-parse --abbrev-ref HEAD)" "$RECORD"

if [[ $PUSH == true ]]; then
  git push origin "$(git rev-parse --abbrev-ref HEAD)"
else
  printf 'Not pushed. Run with --push, or push yourself before releasing.\n'
fi

printf '\nNext: ./release.sh --dry-run\n'
